version: '3'

services:
  multitokenfrontend-stage:
    image: $CI_REGISTRY_IMAGE
    container_name: multitokenfrontend-stage
    restart: always
    expose:
      - "80"
    environment:
      VIRTUAL_HOST: $VIRTUAL_HOST
      LETSENCRYPT_HOST: $LETSENCRYPT_HOST
      LETSENCRYPT_EMAIL: $LETSENCRYPT_EMAIL

networks:
  default:
    external:
      name: frontend_default
